version: "3.9"
services:
    postgres:
        image: postgres:14.8
        environment:
            POSTGRES_DB: "dropsale-data"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "root"
        ports:
            - "5432:5432"
        volumes:
            - ./database/postgres-data:/var/lib/postgresql/data
        container_name: dropsale-postgres
